### ISSUE TITLE
GCP Load Balancer CORS misleading config

### ISSUE THREAD

**Issue by xSAVIKx** [openreplay/documentation#20]
It is stated in the docs that one should add `Access-Control-Allow-Origin` response header in the load balancer config:
https://github.com/openreplay/documentation/blob/314b959edd3b90b3586a380d1a60f4cf9b46f5cc/src/pages/en/deployment/deploy-gcp.mdx?plain=1#L56

But the docs do not specify a particular value or the result of adding such a config which can be very misleading.

Essentially, by specifying a custom response header we're asking the load balancer to update all responses sent back to the callers and forcefully add the noted header (with an empty value) to each and every response. And while this is tolerable by the OpenReplay UI, it is not by the apps that will use the OpenReplay API.

As it is [stated](https://docs.openreplay.com/en/configuration/secure-or/#enabling-cors) that by default CORS is enabled and configured with `*` in the OpenReplay ingress controller, I highly recommend removing the header config part from the docs as this will lead to much more confusion and unintended behavior. The load balancer can forward all response headers and does that by default.

**Comment by deleteman** [comment]
Thanks for the comment @xSAVIKx , we've removed that step from our guides with the latest deployment that should go live in about 30 minutes.
