### ISSUE TITLE
Azure Load Balancer instructions page error

### ISSUE THREAD

**Issue by gregnye2022** [openreplay/documentation#9]
When following the deployment instructions for deploying to kubernetes there is a link that is intended to show instructions for setting up a load balancer for use with openreplay. When clicking the link I get this error
![image](https://user-images.githubusercontent.com/98043987/180454381-c201c797-8254-4e78-99a9-db6ecdda207f.png)

**Comment by estradino** [comment]
Fixed. Thanks for reporting it.
